"""Small dependency-free analyst workbench served with the API."""

ANALYST_UI = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>IOCForge Analyst Workbench</title>
<style>
:root { color-scheme: dark; --bg:#0b1220; --panel:#121d31; --line:#273650; --ink:#e6edf7; --muted:#9db0ca; --blue:#64b5ff; --red:#ff8686; --amber:#ffd166; --green:#6ee7b7; }
* { box-sizing:border-box } body { margin:0; font:15px system-ui,sans-serif; background:var(--bg); color:var(--ink) } header { padding:24px max(5vw,24px); border-bottom:1px solid var(--line); display:flex; justify-content:space-between; gap:20px; align-items:center } h1 { margin:0; font-size:1.45rem } h2 { margin:0 0 16px; font-size:1.1rem } p { color:var(--muted) } nav { display:flex; gap:8px; flex-wrap:wrap } button, input { font:inherit; border-radius:7px; padding:9px 12px; border:1px solid var(--line) } button { color:var(--ink); background:#1a2b47; cursor:pointer } button:hover,button.active { background:#244d7e; border-color:var(--blue) } input { width:min(640px,100%); background:#091221; color:var(--ink) } main { max-width:1200px; margin:auto; padding:28px 5vw 60px } section[hidden] { display:none } .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:14px; margin-bottom:20px } .card,.panel { background:var(--panel); border:1px solid var(--line); border-radius:10px; padding:16px } .metric { font-size:1.7rem; font-weight:700; color:var(--blue) } .label { color:var(--muted); font-size:.85rem; text-transform:uppercase; letter-spacing:.06em } .panel { margin-top:16px } .row { display:flex; flex-wrap:wrap; gap:10px; align-items:center } table { width:100%; border-collapse:collapse } th,td { text-align:left; padding:9px; border-bottom:1px solid var(--line); vertical-align:top } th { color:var(--muted); font-size:.8rem } .status { padding:3px 8px; border-radius:12px; display:inline-block; background:#24364f } .malicious { color:var(--red) } .suspicious { color:var(--amber) } .clean { color:var(--green) } .error { color:var(--red); white-space:pre-wrap } .list { margin:0; padding-left:20px } .empty { color:var(--muted); padding:12px 0 } code { color:#b9d7ff; overflow-wrap:anywhere } @media(max-width:600px) { header { align-items:flex-start; flex-direction:column } th:nth-child(4),td:nth-child(4) { display:none } }
</style></head><body>
<header><div><h1>IOCForge Analyst Workbench</h1><p>Evidence-led indicator triage and investigation context.</p></div><nav aria-label="Workbench sections"><button class="active" data-view="dashboard">Dashboard</button><button data-view="search">IOC search</button><button data-view="history">History</button><button data-view="cases">Investigations</button></nav></header>
<main>
<section id="dashboard"><h2>Operational dashboard</h2><div class="grid" id="metrics"></div><div class="panel"><h2>Provider health</h2><div id="providers"></div></div><div class="panel"><h2>Recent enrichment</h2><div id="recent"></div></div></section>
<section id="search" hidden><h2>IOC search</h2><form id="search-form" class="row"><input id="ioc" required placeholder="Domain, URL, IP, hash, email, CVE, ASN…" aria-label="Indicator of compromise"><button>Enrich indicator</button></form><div id="result"></div></section>
<section id="history" hidden><h2>Enrichment history</h2><div id="history-data"></div></section>
<section id="cases" hidden><h2>Investigations</h2><div id="case-data"></div></section>
</main>
<script>
const API = '/api/v1';
const byId = id => document.getElementById(id);
function clear(node) { node.replaceChildren(); }
function node(tag, value, className) { const item = document.createElement(tag); if (value !== undefined) item.textContent = value; if (className) item.className = className; return item; }
function table(headers, rows) { const t=document.createElement('table'), head=document.createElement('thead'), body=document.createElement('tbody'), tr=document.createElement('tr'); headers.forEach(h=>tr.append(node('th',h))); head.append(tr); rows.forEach(row=>{const r=document.createElement('tr'); row.forEach(cell=>{const c=document.createElement('td'); if (cell instanceof Node) c.append(cell); else c.textContent=cell ?? '—'; r.append(c)}); body.append(r)}); t.append(head,body); return t; }
function empty(message) { return node('p', message, 'empty'); }
async function api(path, options) { const response=await fetch(API+path, options); if (!response.ok) { const body=await response.json().catch(()=>({})); throw new Error(typeof body.detail==='string' ? body.detail : `Request failed (${response.status})`); } return response.json(); }
function renderError(target, error) { clear(target); target.append(node('p', error.message, 'error')); }
function verdict(value) { return node('span', value || 'unknown', `status ${value || ''}`); }
function renderList(title, values) { const panel=node('div', undefined, 'panel'); panel.append(node('h2', title)); if (!values || !values.length) panel.append(empty('None recorded.')); else { const list=node('ul', undefined, 'list'); values.forEach(value=>list.append(node('li', typeof value==='string' ? value : JSON.stringify(value)))); panel.append(list); } return panel; }
async function loadDashboard() { const target=byId('dashboard'); try { const data=await api('/dashboard'); const metrics=byId('metrics'); clear(metrics); const verdicts=data.verdict_counts || {}; const investigation=data.investigation_counts || {}; [['Indicators enriched', Object.values(verdicts).reduce((a,b)=>a+b,0)], ['Open investigations', investigation.open || 0], ['Ready providers', (data.providers||[]).filter(p=>p.enabled && p.healthy).length], ['Providers configured', (data.providers||[]).length]].forEach(([label,value])=>{const card=node('div',undefined,'card');card.append(node('div',label,'label'),node('div',String(value),'metric'));metrics.append(card)}); const providers=byId('providers');clear(providers); providers.append((data.providers||[]).length ? table(['Provider','Status','Reliability','Detail'], data.providers.map(p=>[p.name, verdict(p.enabled ? (p.healthy ? 'ready' : 'degraded') : 'disabled'), p.reliability ?? '—', p.detail ?? p.last_error ?? '—'])) : empty('No providers are configured.')); const recent=byId('recent');clear(recent); const entries=data.recent_enrichments || []; recent.append(entries.length ? table(['Indicator','Verdict','Score','Looked up'], entries.map(e=>[e.ioc,verdict(e.verdict),e.score,e.looked_up_at])) : empty('No enrichment has been recorded yet.')); } catch(error) { renderError(target,error); } }
function renderResult(data, relationships) { const target=byId('result'); clear(target); const summary=node('div',undefined,'panel'); summary.append(node('h2', data.ioc),node('p', `${data.ioc_type} · ${data.confidence} confidence · scoring ${data.scoring_version}`)); const grid=node('div',undefined,'grid'); [['Verdict',data.verdict],['Score',data.score],['Recommended action',data.recommended_action]].forEach(([label,value])=>{const card=node('div',undefined,'card');card.append(node('div',label,'label'), label==='Verdict'?verdict(value):node('div',String(value),'metric'));grid.append(card)}); summary.append(grid); target.append(summary,renderList('Supporting evidence',data.evidence),renderList('Counter-evidence',data.counter_evidence),renderList('No-data sources',data.no_data),renderList('Provider errors',data.errors)); const source=node('div',undefined,'panel');source.append(node('h2','Source breakdown'));source.append(data.sources?.length ? table(['Source','Status','Summary'],data.sources.map(s=>[s.source || s.name || 'unknown',s.status || 'returned',s.summary || JSON.stringify(s.data ?? s)])) : empty('No provider responses.'));target.append(source); const related=node('div',undefined,'panel');related.append(node('h2','IOC relationships'));related.append(relationships.length ? table(['Source','Relationship','Target','Confidence'],relationships.map(r=>[r.source_ioc,r.relationship_type,r.target_ioc,r.confidence])) : empty('No persisted relationships for this indicator.'));target.append(related); }
byId('search-form').addEventListener('submit', async event=>{ event.preventDefault(); const target=byId('result'); clear(target); target.append(empty('Enriching indicator…')); try { const data=await api('/enrich',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ioc:byId('ioc').value})}); const relationships=await api(`/indicators/${encodeURIComponent(data.ioc)}/relationships`).catch(()=>[]); renderResult(data,relationships); } catch(error) { renderError(target,error); } });
async function loadHistory() { const target=byId('history-data');clear(target);target.append(empty('Loading history…'));try {const data=await api('/history?limit=50');clear(target);target.append(data.items?.length ? table(['Indicator','Verdict','Score','Looked up'],data.items.map(e=>[e.ioc,verdict(e.verdict),e.score,e.looked_up_at])) : empty('No enrichment history yet.'));}catch(error){renderError(target,error)}}
async function loadCases() { const target=byId('case-data');clear(target);target.append(empty('Loading investigations…'));try {const data=await api('/investigations');clear(target);target.append(data.items?.length ? table(['ID','Title','Status','Indicators'],data.items.map(i=>[i.id,i.title,i.status,(i.indicators||[]).join(', ')])) : empty('No investigations yet.'));}catch(error){renderError(target,error)}}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));button.classList.add('active');document.querySelectorAll('main section').forEach(section=>section.hidden=section.id!==button.dataset.view);if(button.dataset.view==='dashboard')loadDashboard();if(button.dataset.view==='history')loadHistory();if(button.dataset.view==='cases')loadCases();}));
loadDashboard();
</script></body></html>"""
